

defaults:
  - scope:
      path: ""
    values:
      layout: "default"


sass:
    sass_dir: _sass

#site variables

title: FOSS4G Perth
description: FOSS4G Perth - open source geospatial conference, Perth, Western Australia
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# twitter_username: foss4g_perth
# github_username:
slack: 'Geogeeks'
linkedin: 'FOSS4G Perth'
email: 'admin@foss4g-perth.org'
header_logo: 'assets/img/FOSS4G_Perth_logo_black.png'
youTube: 'https://www.youtube.com/@FOSS4GPerth/videos'

# Google Analytics
google_analytics: G-JCXFYD6H36
